// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiFinalProject.Data;

#nullable disable

namespace WebApiFinalProject.Migrations
{
    [DbContext(typeof(ApplicaionDbContext))]
    [Migration("20250823150314_Vehicle")]
    partial class Vehicle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiFinalProject.Models.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Allows natural light in.",
                            Name = "Sunroof",
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Connects iPhone to the car's display.",
                            Name = "Apple CarPlay",
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Provides better traction on slick roads.",
                            Name = "All-Wheel Drive",
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Advanced driver assistance system.",
                            Name = "Autopilot",
                            VehicleId = 3
                        },
                        new
                        {
                            Id = 5,
                            Description = "Provides warmth during cold weather.",
                            Name = "Heated Seats",
                            VehicleId = 4
                        });
                });

            modelBuilder.Entity("WebApiFinalProject.Models.Owner", b =>
                {
                    b.Property<int>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OwnerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OwnerId");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            OwnerId = 1,
                            Address = "Andra Pradesh",
                            Age = 23,
                            Email = "yesh@gmail.com",
                            Name = "Yeshwanth"
                        },
                        new
                        {
                            OwnerId = 2,
                            Address = "Chickballapur",
                            Age = 27,
                            Email = "cham@gmail.com",
                            Name = "Chaman"
                        },
                        new
                        {
                            OwnerId = 3,
                            Address = "Bangalore",
                            Age = 25,
                            Email = "hari@gmail.com",
                            Name = "Harish"
                        });
                });

            modelBuilder.Entity("WebApiFinalProject.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("WebApiFinalProject.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "Charan@123",
                            RoleId = 1,
                            Username = "Charan"
                        },
                        new
                        {
                            Id = 2,
                            Password = "Hadiya@456",
                            RoleId = 2,
                            Username = "Hadiya"
                        });
                });

            modelBuilder.Entity("WebApiFinalProject.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("date")
                        .HasColumnType("date");

                    b.HasKey("VehicleId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            VehicleId = 1,
                            Make = "Toyota",
                            Model = "Camry",
                            OwnerId = 1,
                            date = new DateOnly(2000, 8, 21)
                        },
                        new
                        {
                            VehicleId = 2,
                            Make = "Honda",
                            Model = "CR-V",
                            OwnerId = 2,
                            date = new DateOnly(2002, 5, 11)
                        },
                        new
                        {
                            VehicleId = 3,
                            Make = "Tesla",
                            Model = "Model 3",
                            OwnerId = 1,
                            date = new DateOnly(2021, 3, 1)
                        },
                        new
                        {
                            VehicleId = 4,
                            Make = "Ford",
                            Model = "Mustang",
                            OwnerId = 3,
                            date = new DateOnly(2025, 9, 27)
                        });
                });

            modelBuilder.Entity("WebApiFinalProject.Models.Feature", b =>
                {
                    b.HasOne("WebApiFinalProject.Models.Vehicle", "Vehicle")
                        .WithMany("Features")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("WebApiFinalProject.Models.User", b =>
                {
                    b.HasOne("WebApiFinalProject.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WebApiFinalProject.Models.Vehicle", b =>
                {
                    b.HasOne("WebApiFinalProject.Models.Owner", "Owner")
                        .WithMany("Vehicles")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("WebApiFinalProject.Models.Owner", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("WebApiFinalProject.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("WebApiFinalProject.Models.Vehicle", b =>
                {
                    b.Navigation("Features");
                });
#pragma warning restore 612, 618
        }
    }
}
